server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerup
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
