server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: 123456


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  cloud:
    config:
      enabled: false
appDescription: "Pragma Powerup"
appVersion: "1.0.0"

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}
